from py_beep_music import *

pt1=[(C5,VIERTEL,STACCATO),(As4,VIERTEL,STACCATO),(C5,VIERTEL,STACCATO),(G4,VIERTEL,STACCATO),(Ds4,VIERTEL,STACCATO),(G4,VIERTEL,STACCATO),(C4,HALBE,STACCATO)]
pt2=[(C5,VIERTEL,STACCATO),(D5,VIERTEL,STACCATO),(Ds5,VIERTEL,STACCATO),(D5,VIERTEL,STACCATO),(Ds5,VIERTEL,STACCATO),(C5,VIERTEL,STACCATO),(D5,VIERTEL,STACCATO),(C5,VIERTEL,STACCATO),(D5,VIERTEL,STACCATO),(As4,VIERTEL,STACCATO),(C5,VIERTEL,STACCATO),(As4,VIERTEL,STACCATO),(C5,VIERTEL,STACCATO),(Gs4,VIERTEL,STACCATO),(C5,HALBE,STACCATO)]


tune = pt1 + pt1 + pt2
tune = tune + tune

play(tune,340)
