from py_beep_music import *

pt1=[(C5,VIERTEL),(As4,VIERTEL),(C5,VIERTEL),(G4,VIERTEL),(Ds4,VIERTEL),(G4,VIERTEL),(C4,HALBE)]
pt2=[(C5,VIERTEL),(D5,VIERTEL),(Ds5,VIERTEL),(D5,VIERTEL),(Ds5,VIERTEL),(C5,VIERTEL),(D5,VIERTEL),(C5,VIERTEL),(D5,VIERTEL),(As4,VIERTEL),(C5,VIERTEL),(As4,VIERTEL),(C5,VIERTEL),(Gs4,VIERTEL),(C5,HALBE)]


tune = pt1 + pt1 + pt2
tune = tune + tune

play(tune,240)
