from py_beep_music import *

pt1=[(C4,VIERTEL),(As3,VIERTEL),(C4,VIERTEL),(G3,VIERTEL),(Ds3,VIERTEL),(G3,VIERTEL),(C3,VIERTEL)]
pt2=[(C4,VIERTEL),(D4,VIERTEL),(Ds4,VIERTEL),(D4,VIERTEL),(Ds4,VIERTEL),(C4,VIERTEL),(D4,VIERTEL),(C4,VIERTEL),(D4,VIERTEL),(As3,VIERTEL),(C3,VIERTEL),(As3,VIERTEL),(C3,VIERTEL),(Gs3,VIERTEL),(C3,VIERTEL),(Gs3,VIERTEL),(C3,VIERTEL)]


tune = pt1 + pt1 + pt2

play(tune, 128)
